In [4]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

In [6]:
dataset = pd.read_csv('train_data.csv')
dataset.head()

TrainNo               TrainName  Type  Distance  Region  Day  DelayInMin  \
0    12004  Lucknow Swarn Shatabdi     0         0       1    1          22   
1    12004  Lucknow Swarn Shatabdi     0         0       1    2          36   
2    12004  Lucknow Swarn Shatabdi     0         0       1    3          32   
3    12004  Lucknow Swarn Shatabdi     0         0       1    4          26   
4    12004  Lucknow Swarn Shatabdi     0         0       1    5          37   

   noUse  
0   12.0  
1   26.0  
2   22.0  
3   16.0  
4   27.0

In [14]:
# dataset.drop(columns=['Region'])
# del dataset['noUse']
# del dataset['Day']
dataset

TrainNo               TrainName  Type  Distance  Region  DelayInMin
0      12004  Lucknow Swarn Shatabdi     0         0       1          22
1      12004  Lucknow Swarn Shatabdi     0         0       1          36
2      12004  Lucknow Swarn Shatabdi     0         0       1          32
3      12004  Lucknow Swarn Shatabdi     0         0       1          26
4      12004  Lucknow Swarn Shatabdi     0         0       1          37
..       ...                     ...   ...       ...     ...         ...
449    12445          Uttar S Kranti     0         1       3          10
450    12445          Uttar S Kranti     0         1       3           5
451    12445          Uttar S Kranti     0         1       3           0
452    12445          Uttar S Kranti     0         1       3          14
453    12445          Uttar S Kranti     0         1       3          19

[454 rows x 6 columns]

In [15]:
X = dataset.iloc[:, 2:5].values
y = dataset.iloc[:, -1].values

In [17]:
X[53]

array([1, 0, 1], dtype=int64)

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [19]:
X[53]

array([1., 0., 0., 1., 0.])

In [20]:
y[53]

55

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

In [22]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [23]:
print(X_test[1])

[1. 0. 0. 1. 0.]


In [24]:
y_pred = regressor.predict(X_test)
print(y_pred)

[ 89.45989478 124.84171362 -95.03511163  61.00358671   0.67514696
 185.17015337  29.13145503  61.00358671  61.00358671 124.84171362
  21.80002749 185.17015337  61.00358671  61.00358671 185.17015337
  29.13145503  89.45989478  29.13145503  29.13145503  21.80002749
  21.80002749 -95.03511163  57.18184634  89.45989478 -95.03511163
 185.17015337  61.00358671  21.80002749 -95.03511163  61.00358671
  61.00358671  21.80002749 -95.03511163 124.84171362 185.17015337
  61.00358671 -38.52841226   0.67514696   0.67514696   0.67514696
  21.80002749   0.67514696   0.67514696 -95.03511163  61.00358671
  61.00358671 185.17015337 185.17015337 185.17015337 124.84171362
  57.18184634 -38.52841226  21.80002749  29.13145503  89.45989478
 124.84171362  21.80002749  29.13145503 124.84171362  61.00358671
 185.17015337  21.80002749   0.67514696 124.84171362  61.00358671
 185.17015337 185.17015337 -38.52841226  61.00358671  61.00358671
 185.17015337 -38.52841226   0.67514696 185.17015337 124.84171362
  21.80002

In [29]:
x = [[0,0,1,0,0]]
print(regressor.predict(x))

[-38.52841226]
